### ISSUE TITLE
MySQL SchemaDefLoader skip zero values

### ISSUE THREAD

**Issue by mcs07** [rcsb/py-rcsb_db#19]
It seems that the `if` statement on line 420 in SchemaDefLoader means that integers with a value of `0` get skipped because then `row[id]` evaluates to `False`.
https://github.com/rcsb/py-rcsb_db/blob/d465fc231fa967587761d2347f7006df62c8bdb3/rcsb/db/mysql/SchemaDefLoader.py#L418-L423

I think it should be changed to:

```
if row[id] is not None and row[id] != r'\N':
```

Unless it is guaranteed that null values are always transformed to `\N`, in which case the first part of the check could just be removed entirely?

It also looks like the same issue exists in some of the other database loaders, e.g. https://github.com/rcsb/py-rcsb_db/blob/master/rcsb/db/cockroach/CockroachDbLoader.py#L159

**Comment by jdwestbrook** [comment]
Thank you for the report and suggestion. The null handling has been updated in mysql, crate and cockroach loader methods in version 0.52.
