### ISSUE TITLE
pip install fails on macOS

### ISSUE THREAD

**Issue by valasatava** [rcsb/py-rcsb_db#7]
I am unable to install on macOS via pip. I'm running into an issue with wrong MySQL configuration: maybe due to https://bugs.mysql.com/bug.php?id=86971

@jdwestbrook, could you, please, add instructions on how to install this project on mac?

**Comment by jdwestbrook** [comment]
There are wide range of options available for creating a development environment to support Python, MariaDB/MySQL, and MongoDB.  I have added an approach that I am fond of in the package README.

**Comment by valasatava** [comment]
@jdwestbrook, thanks, installing MariaDB package solved my issue.
